- name: Configurung webservers
  hosts: n3
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start httpd
      service:
        name: httpd
        state: started

    - name: Create test.html file
      copy:
        src: /home/ubuntu/test.html
        dest: /var/www/html/test.html

