- name: Configurung webservers
  hosts: centos7
  become: yes

  tasks:
    - name: Install apache2
      yum:
        name: httpd
        state: present

    - name: Start apache2
      service:
        name: httpd
        state: started
