- name: Configurung webservers
  hosts: all
  become: yes

  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Stop apache2
      service:
        name: apache2
        state: started