- name: Install webservers on all nodes
  hosts: all
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Copy test.html file to worker node
      template:
        src: /home/ubuntu/ansiblesaikumar/test.j2
        dest: /var/www/html/test.html
      when: ansible_distribution == "CentOS"




