- name: Install webservers on all nodes
  hosts: all
  become: yes

  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Install httpd
      yum:
        name: httpd
        state: present