- name: Install webservers on all nodes
  hosts: all
  become: yes
  vars:
    first_name: "Sainath"
    my_port: 100

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start httpd
      service:
        name: httpd
        state: started
      when: ansible_distribution == "CentOS"


    - name: Copy test.html file to worker node
      template:
        src: /home/ubuntu/ansiblesaikumar/test.j2
        dest: /var/www/html/test.html

    - name: Copy httpd.conf file
      template:
        src: /home/ubuntu/ansiblesaikumar/httpd.j2
        dest: /etc/httpd/conf/httpd.conf

    - name: Start httpd
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "CentOS"





